### ISSUE TITLE
GoBlockly. I don't know how to build a complete distribution

### ISSUE THREAD

**Issue by tellts** [fixermark/goblockly#1]
Please share the complete distribution of Blockly with integrated Goblockly module.

**Comment by fixermark** [comment]
Hi tellts!

Unfortunately, GoBlockly doesn't directly support any particular Blockly client. Its intent is to run Blockly code generated from some other source. The entrypoint for using this library itself is described in the README under how to use, but to unmarshal the XML you'll need to have some XML to work with.

In my original use case (the Belphanior home automation system), the XML came from running a Blockly client and using the `blockToXml` function, which appears to have since been renamed `blockToDom` and is documented here (https://developers.google.com/blockly/reference/js/Blockly.Xml). I shipped that XML over the network to a Go server that included this library, and it unpacked the XML and fed it to the interpreter.

I hope this will be of use for your case. Note that unfortunately this library is unsupported so I don't plan to make changes if Google has changed Blockly's XML representation.

**Comment by tellts** [comment]
Thanks for the information
